
PREFIX :		<http://agentlab.ru/2019/edu_ontology#>
PREFIX owl:		<http://www.w3.org/2002/07/owl#>
PREFIX rdf:		<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml:		<http://www.w3.org/XML/1998/namespace>
PREFIX xsd:		<http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccso:	<https://w3id.org/ccso/ccso#>
PREFIX skosxl:	<http://www.w3.org/2008/05/skos-xl#>
PREFIX esco:	<http://data.europa.eu/esco/model#>


SELECT ?syll ?module ?method ?topic ?duration
WHERE {
	# Получение списка тем
	?module a ccso:KnowledgeUnit ;
			ccso:lists ?topic .

	# Поучение рпд
	?syll 	a ccso:Syllabus ;
			:consistsOfModules ?module .

	# Определение типа занятия
	?te 	ccso:hasTopic ?topic ;
			ccso:followsTEMethod ?method .

	# Определение длительности занятий
	?topic ccso:duration ?duration .
}

