
PREFIX :		<http://agentlab.ru/2019/edu_ontology#>
PREFIX owl:		<http://www.w3.org/2002/07/owl#>
PREFIX rdf:		<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xml:		<http://www.w3.org/XML/1998/namespace>
PREFIX xsd:		<http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccso:	<https://w3id.org/ccso/ccso#>


SELECT ?module ?method ?topic ?duration
WHERE {
	?module ccso:lists ?topic .
	?course ccso:hasSyllabus ?syll .
	?syll ccso:coversTopic ?topic .
	?te 	ccso:hasTopic ?topic ;
			ccso:followsTEMethod ?method .
	?topic ccso:duration ?duration .
}
